### ISSUE TITLE
Thermal twinbuilder example failing with latest MC version

### ISSUE THREAD

**Issue by jgsdavies** [ansys/pymotorcad#396]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://github.com/user-attachments/assets/bc02443b-f0ef-4d64-9725-309e1b82a647)

### 📝 Steps to reproduce

Run thermal_twinbuilder.py

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

N/A

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
N/A
```

**Comment by HusainAdam** [comment]
Issue not reproducible on my machine, using latest version of main. 
I am utilising latest version of Motor-CAD publicly available, 2024_2_2_1. Code executes successfully:

![image](https://github.com/user-attachments/assets/8f1803c0-4ba4-47c7-8f38-78e1f81b6392)
![image](https://github.com/user-attachments/assets/ae266775-1ea6-452c-b1fa-044285e91361)

resulting output successfully used in TB:
![image](https://github.com/user-attachments/assets/ea2862e1-e39a-4b33-b0f6-c8261be31c5b)

This may be due to changes in Motor-CAD default behaviour in 2025 test release. This has a different default method for "Fluid Heat Flow Method" which results in different output files being written.

@jgsdavies can you please confirm which version of Motor-CAD was used that produced this error?

**Comment by HusainAdam** [comment]
Trying out a fix: check if newer version of Motor-CAD is being used, and if so, ensure the old working heat flow method is used.
